### ISSUE TITLE
Allow RootDeterministicKey generation from human seed

### ISSUE THREAD

**Issue by ThePiachu** [rubblelabs/ripple#12]
The human seed ("shHM53KPZ87Gwdqarm1bAmPeXg8Tn") is used for some commands (Sign, Submit) and thus it would be nice if it was supported in a straightforward fashion like the []byte seed ("71ED064155FFADFA38782C5E0158CB26").

**Comment by donovanhide** [comment]
Fixed in 48f3c5299a5d2fe666822f9c80145305170063f5
