### ISSUE TITLE
Add a TxBase function for signing the transaction

### ISSUE THREAD

**Issue by ThePiachu** [rubblelabs/ripple#13]
It would be useful if there was a straightforward

func (t *TxBase) Sign(secret string)

function that would sign a transaction with a given secret / seed . This would allow offline signing of transactions much easier than the current, manual route.

**Comment by ThePiachu** [comment]
I guess the functionality could look something like this:

	type SignableTransaction interface {
		data.Signer
		GetBase() *data.TxBase
	}

	func SignRubbleTransaction(tx SignableTransaction, key *crypto.RootDeterministicKey) (error) {
		var sequence int32
		sequence = 0
		priv, err := key.GenerateAccountKey(sequence)
		if err!=nil {
			return err
		}
		id, err := key.GenerateAccountId(sequence)
		if err!=nil {
			return err
		}
		pub, err := priv.PublicAccountKey()
		if err!=nil {
			return err
		}

		base := tx.GetBase()
		base.SigningPubKey = new(data.PublicKey)
		copy(base.Account[:], id.Payload())
		copy(base.SigningPubKey[:], pub.Payload())
		tx.GetBase().TxnSignature = &data.VariableLength{}
		err = data.Sign(tx, priv)
		if err!=nil {
			return err
		}

		return nil
	}

And all the various transaction types / transaction base could have a function like:

    func (t *TxBase)Sign(key *crypto.RootDeterministicKey) (error) {return Sign(t, key)}

**Comment by donovanhide** [comment]
Made simpler in 48f3c5299a5d2fe666822f9c80145305170063f5
