### ISSUE TITLE
Add a TxBase interface for handling basic operations on all transaction types

### ISSUE THREAD

**Issue by ThePiachu** [rubblelabs/ripple#16]
It would be useful to have some sort of

    type TxBaseInterface interface

for handling all of the transaction types in a uniform fashion without having to write a lot of switches into the functions. All in all, it would probably boil down to adding setters to the struct variables.

An example use for this type of interface is creating a transaction offline. Whether it's Payment, AccountSet or the like, after it is assembled, it would be beneficial to be able to call

    func (t *TxBase)SetHash(hash Hash256) {t.Hash = hash}

rather than having to call

	func SetHash(t interface{}, hash Hash256) {
		switch t := t.(type) {
		default:
			return
		case TxBase:
			t.Hash = hash
		case Payment:
			t.Hash = hash
		case AccountSet:
			t.Hash = hash
		case SetRegularKey:
			t.Hash = hash
		case OfferCreate:
			t.Hash = hash
		case OfferCancel:
			t.Hash = hash
		case TrustSet:
			t.Hash = hash
		case SetFee:
			t.Hash = hash
		case Amendment:
			t.Hash = hash
		}
	}

**Comment by lukecyca** [comment]
In your example, I'm not sure why you would want to accept `interface{}` into the function and then silently ignore non-Transaction types. If you use the more appropriate `Transaction` interface type, you can achieve the same thing more easily and more safely:

```go
func SetHash(t Transaction, hash Hash256) {
    *t.GetHash() = hash
}
```
or alternatively:
```go
func SetHash(t Transaction, hash Hash256) {
    t.GetBase().Hash = hash
}
```

**Comment by ThePiachu** [comment]
Ah, didn't notice that GetHash() returns a pointer rather than a value.

That being said, there are other variables that one might need to set - for example Sequence.

**Comment by donovanhide** [comment]
What's wrong with:
```
base:=t.GetBase()
base.Hash = hash
base.Sequence = sequence
```
The idea of TxBase is just to store common fields, not add functions which can be applied to the outer struct. That's what single purpose interfaces like Transaction, Hashable, Signer, et al are for:
https://github.com/rubblelabs/ripple/blob/master/data/interface.go
Go doesn't really need getters and setters. Languages like Java, C# and C++ enjoy encapsulation, but Go's rules are much simpler with regard to exporting, so just follow the simplicity :-)

**Comment by ThePiachu** [comment]
Oh yeah, I guess that would work. My C++ / Java habits die slowly ;).
