### ISSUE TITLE
RipplePathFind implementation is not right？

### ISSUE THREAD

**Issue by yxxyun** [rubblelabs/ripple#17]
RipplePathFind(src, dest data.Account, amount data.Amount, srcCurr *[]data.Currency)

but srcCurr should be *[]data.Asset according to https://ripple.com/build/rippled-apis/#ripple-path-find

**Comment by donovanhide** [comment]
Patch welcome :-)

I can honestly say that I've never used rippled's path-finding. It doesn't provide particularly good paths :-)
