### ISSUE TITLE
Calculating ledger hashes

### ISSUE THREAD

**Issue by stevenroose** [rubblelabs/ripple#18]
Like demonstrated [here](https://github.com/ripple/ripple-lib-java/blob/master/ripple-core/src/main/java/com/ripple/core/types/ledger/LedgerHeader.java#L66) in Java, the ledger hash is created by calculating the SHA512-HALF of the hash prefix and all the ledger header fields.

I'm trying to do the same in Go:
```go
ledgerResult, err := remote.Ledger(sequence, false)
ledgerHeader := ledgerResult.Ledger.LedgerHeader
ledgerHash := ledgerResult.Ledger.Hash
buf := new(bytes.Buffer)
binary.Write(buf, binary.BigEndian, data.HP_LEDGER_MASTER)
binary.Write(buf, binary.BigEndian, ledgerHeader)
calculatedLedgerHash := data.NewHash256(crypto.Sha512Half(headerBytes))
```

For some reason, though, the `calculatedLedgerHash` differs from `ledgerHash`. So either the `LedgerHeader` struct is not correctly formatted or not correctly serialized, or there is something wrong with my logic.

**Comment by donovanhide** [comment]
Been ages since I looked at any of this, but headerBytes is not defined in your example. Provide a compilable example and I'll take a look.

Also, the logic is here:

https://github.com/rubblelabs/ripple/blob/master/data/encoder.go#L13

and docs here: 

https://godoc.org/github.com/rubblelabs/ripple/data

**Comment by stevenroose** [comment]
I was not aware of the encoder logic. And I can't seem to find a way to hash a ledger header with it. I don't think a LedgerHeader is a Hashable?

This is the code I'm testing with (it's messy as I'm new to Go and I only want to get to know the logic to use it in another language): https://gist.github.com/stevenroose/9025f7bc02c882cc5672cf69f354bb5c

**Comment by stevenroose** [comment]
Should I use this thing? https://github.com/rubblelabs/ripple/blob/5a906508287e2550308e51d1310211a474035aa3/data/factory.go#L37

I have no idea what that does..

**Comment by donovanhide** [comment]
https://gist.github.com/donovanhide/62014ceeffc18d29f5a57ccc86b364f2

And the just pushed commit, should give you the matching hashes. I only ever tested the code against the binary data, and not JSON responses.

Bear in mind that this library was only written to try and understand the Ripple protocol over 2 years ago. Not really planning on supporting it. The Ripple protocol is very much undocumented and subject to change without advance notification, so good luck with your endeavours :-)

**Comment by stevenroose** [comment]
@donovanhide Thanks a lot, that seems to work.

If only rippled had an API that only communicates in binary. My next challenge is to do the same trick for a transaction.

**Comment by donovanhide** [comment]
Closing :-)
