### ISSUE TITLE
"invalid memory address or nil pointer dereference" when inspecting offers

### ISSUE THREAD

**Issue by dncohen** [rubblelabs/ripple#19]
Hi, thanks for sharing these golang libraries!

I've got some code looking a the results of a call to remote.BookOffers().  When I try to print the offers returned, I see "invalid memory address or nil pointer dereference".  And I'm having trouble figuring out which pointer is bad (and, whether it is even a problem).

The problem does not occur in your example tools/book/book.go.  I think because it uses some terminal magic to display results.  If in that program you replace

    terminal.Println(offer, terminal.Default)

with 

    fmt.Println(offer)

then you'll see the problem.  With that change, run `go run book.go BTC/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B USD/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B | less` and notice the output starts with

    {{{Offer 7BA87E4EBB3607F68B541EA10216436A65F5A8C0B6489CCB263CE2598DEEEDF9 388EF627A09A6DE42F5302A63CFFD0D3C8FECCBDDE774D3CFD4FE2AD4FD13C68 0xc4201a2930 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000000000000000000000000000} 00000000 rUp8CvtneUUL6qYaxfZwUHg2cwYuo5jugG 0xc4201a2940 3041.9574925631/USD/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B 5/BTC/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B 6EAB7C172DEFA430DBFAD120FDC373B5F5AF8B191649EC9857159D49D7883938 0xc4201a28f8 0xc4201a2918 <nil>} 24.550174 608.39149851262 %!v(PANIC=runtime error: invalid memory address or nil pointer dereference) %!v(PANIC=runtime error: invalid memory address or nil pointer dereference)}

There are other offers in the book which do not render this panic.  I'm not yet sure why some have this problem and others do not.  Any ideas?

**Comment by donovanhide** [comment]
It's probably the taker_gets_funded and taker_pays_funded fields you get when an offer is either wholly or partially unfunded. This commit should make your bad fmt expansion go away by keeping nil pointer for absent fields:

https://github.com/rubblelabs/ripple/commit/111a4c22b018a097fdb6678bd6f5ff8942086dfd#diff-fe2cb3bde0f9bc7820fbfc9a156bc081L44

But, to be honest it's better to define your own formatting with fixed widths, like the terminal package does, or you'll just end up with some oddly formatted garbage :-)

By the way, if you have add `GOPATH/bin` to your `PATH` you can do:

```go install github.com/rubblelabs/ripple/tools/book```

and then just:

```book BTC/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B USD/rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B```

Are you using Go for internal work at Ripple now?

**Comment by donovanhide** [comment]
As an addendum, in the spirit of healthy open source software, it would be great if you could contribute patches and pull requests rather than fork the repo and avoid all this unnecessary renaming:

https://github.com/dncohen/ripple-go/commit/df7bf842a37d3b6880ca54db53f58b48ac546e2f

If you need help setting up your Go environment, I can help :-)

**Comment by dncohen** [comment]
Thanks for the explanation.  I'll check that commit when time permits.

I understand the `PATH`.  Only using `go run ...` when testing changes.

> Are you using Go for internal work at Ripple now?

Nope.  Everything golang is extracurricular.

> If you need help setting up your Go environment, I can help :-)

If there is a way to avoid those global search/replace in a fork, I would love to know what it is!

I'm happy to submit pull requests.  I have very little for you, at this point.  These two nuggets possibly worth merging:

https://github.com/dncohen/ripple-go/commit/1ab5ab5f83108d2334a5b5950cb8dce3b227e7ed

https://github.com/dncohen/ripple-go/commit/7d9bb602ba639f8cd3e016512d22db84e4437df3

Want a PR for each?

**Comment by dncohen** [comment]
Ah, just now I see your link to http://code.openark.org/blog/development/forking-golang-repositories-on-github-and-managing-the-import-path

Will look into it.

**Comment by donovanhide** [comment]
Yep, PR's welcome, but adopt one of the two solutions in that linked page first. You'll never look back afterwards :-)

Please close this issue when you have a chance to see if it fixes your issue. Sorry for the jumbled commit, you caught me mid some other work :-)

**Comment by dncohen** [comment]
Merging the latest does clear up this issue.  Nice.

I still have the "unnecessary renaming" in my fork, for the time being.  I have some other code importing my fork, and I don't want to break that build.  Will clean that up first.  

With your recent changes, I may not need this fork at all.  It is likely to go away.  But, if I encounter anything that I can patch, I'll make more PRs.
